dist: xenial
language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get install -y  g++-multilib-arm-linux-gnueabihf gcc-multilib-arm-linux-gnueabihf
script: make arch=arm platform=classic_armv8_a35 CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ -f Makefile.libretro 
